### PR TITLE
New Request-Reply C# Example

### PR DESCRIPTION
**Pull request by alexcamposruiz**
### Summary
This PR adds a new example for Request-Reply. It is implemented in C#.

### Details and comments
Note that the same example is available in other languages in the Connext installer.

### CODE REVIEW

**Comment by lulivi** [comment]
Hey @alexcamposruiz can you fix the [Markdown issues](https://github.com/rticommunity/rticonnextdds-examples/runs/5029040081?check_suite_focus=true)?

**Comment by ManuelJNunez** [comment]
Hey @alexcamposruiz we fixed the clang-format issue, try to merge develop into your branch.

**Review by luisrg-rti — APPROVED** [review]
Check that final changes made to the API after this PR was created don't break anything

**Comment by ManuelJNunez** [comment]
Now it's showing the real issues. Install clang-format==13.0.0 using pip and execute `clang-format --style=file -i examples/connext_dds/request_reply/cs/PrimesProgram.cs examples/connext_dds/request_reply/cs/PrimesReplier.cs examples/connext_dds/request_reply/cs/PrimesRequester.cs` to fix the linter issues.

**Comment by alexcamposruiz** [comment]
> Now it's showing the real issues. Install clang-format==13.0.0 using pip and execute `clang-format --style=file -i examples/connext_dds/request_reply/cs/PrimesProgram.cs examples/connext_dds/request_reply/cs/PrimesReplier.cs examples/connext_dds/request_reply/cs/PrimesRequester.cs` to fix the linter issues.

This is applying C++ linting options to C# code. The suggested changes are against the typical C# conventions that we also follow.

**Comment by lulivi** [comment]
@alexcamposruiz shouldn't we lint the C# code then?

**Comment by alexcamposruiz** [comment]
> @alexcamposruiz shouldn't we lint the C# code then?

We lint it during development. Is that automated here?

**Comment by ManuelJNunez** [comment]
> > @alexcamposruiz shouldn't we lint the C# code then?
> 
> We lint it during development. Is that automated here?

Which linter are you using?

**Comment by alexcamposruiz** [comment]
> > > @alexcamposruiz shouldn't we lint the C# code then?
> > 
> > 
> > We lint it during development. Is that automated here?
> 
> Which linter are you using?

The Microsoft one (from the Microsoft C# extension for VSC). The options are in connextdds/dds_dotnet.2.0/omnisharp.json.

**Comment by ManuelJNunez** [comment]
> > > > @alexcamposruiz shouldn't we lint the C# code then?
> > > 
> > > 
> > > We lint it during development. Is that automated here?
> > 
> > 
> > Which linter are you using?
> 
> The Microsoft one (from the Microsoft C# extension for VSC). The options are in connextdds/dds_dotnet.2.0/omnisharp.json.

Thank you @alexcamposruiz, ignore the linter for now. We will implement in the future a solution with the Microsoft's linter.

**Pull request merged**
