### PR TITLE
Feature/542: Fix Python code

### PR DESCRIPTION
**Pull request by lulivi**
### Summary

Fix code formatting.

### Checks

-   [x] I have updated the documentation accordingly.
-   [x] I have read the [CONTRIBUTING](https://github.com/rticommunity/rticonnextdds-examples/blob/develop/CONTRIBUTING.md) document.

### CODE REVIEW

**Review by alexcamposruiz — APPROVED** [review]

**Comment by alexcamposruiz** [comment]
Thanks for fixing it @lulivi!

**Comment by alexcamposruiz** [comment]
Just one thing. This update should go to master, not develop, right?

**Review by alexcamposruiz — CHANGES_REQUESTED** [review]
merge to master, not develop.

**Comment by lulivi** [comment]
@alexcamposruiz done!

**Review by alexcamposruiz — APPROVED** [review]

**Pull request merged**
