### PR TITLE
Adds the hability to select the speficic example subfolders to build

### LINKED ISSUE #533: [ENH] Define variables for each example folder with the list of avaliable examples
### Enhancement description

For each examples folder:

- `connext_dds`: `BUILD_EXAMPLES_CONNEXT_DDS`
- `persistence_service`: `BUILD_EXAMPLES_PERSISTENCE_SERVICE`
- `recording_service`: `BUILD_EXAMPLES_RECORDING_SERVICE`
- `routing_service`: `BUILD_EXAMPLES_ROUTING_SERVICE`

This way, we will be settings all the available examples of each folder in those variables and can be overwritten by manually specifying it when building.

For example, we could run:

```shell
cd examples
mkdir build
cd build

cmake [...] -DBUILD_EXAMPLES_CONNEXT_DDS="asyncwaitset;batching;builtin_qos_profiles" ..
```

So this way, from the [list of all the examples/connext_dds example directories](https://github.com/rticommunity/rticonnextdds-examples/blob/9b4fd1fb05d180c86c4f307c63a66d840c4201f0/examples/connext_dds/CMakeLists.txt#L59-L113) we will build only the selected ones.

### PR DESCRIPTION
**Pull request by lulivi**
Closes #533

### Summary

Added one CMake variable for each example folder built in CI in order to be able to overwrite the selected examples.

### Details and comments

See #533 .

### Checks

-   [x] I have updated the documentation accordingly.
-   [x] I have read the [CONTRIBUTING](https://github.com/rticommunity/rticonnextdds-examples/blob/develop/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by lulivi** [comment]
@fgaranda @ManuelJNunez maybe we should change the name of one of these two variables:

- `BUILD_EXAMPLES_RECORDING_SERVICE`: list of the examples to build in the `recording_service` directory
- `CONNEXTDDS_BUILD_RECORDING_SERVICE_EXAMPLES`: flag to include or not the `recording_service` directory

(Same with the other directories)

**Comment by lulivi** [comment]
> @fgaranda @ManuelJNunez maybe we should change the name of one of these two variables:
> 
> * `BUILD_EXAMPLES_RECORDING_SERVICE`: list of the examples to build in the `recording_service` directory
> * `CONNEXTDDS_BUILD_RECORDING_SERVICE_EXAMPLES`: flag to include or not the `recording_service` directory
> 
> (Same with the other directories)

@fgallegosalido what do you think, since you name that variables in the past?

**Comment by fgallegosalido** [comment]
Do you have any proposed names? I'm not 100% convinced about `BUILD_EXAMPLES_RECORDING_SERVICE` as a name for a list.

**Comment by lulivi** [comment]
> Do you have any proposed names? I'm not 100% convinced about `BUILD_EXAMPLES_RECORDING_SERVICE` as a name for a list.

What about `CONNEXTDDS_RECORDING_SERVICE_EXAMPLES` or `CONNEXTDDS_SELECTED_RECORDING_SERVICE_EXAMPLES`? Maybe something shorter? seems like a very long name for a variable.

**Comment by fgallegosalido** [comment]
I like `CONNEXTDDS_RECORDING_SERVICE_EXAMPLES` better.

**Review by fgaranda — APPROVED** [review]

**Pull request merged**
