### PR TITLE
rticommunity#283: Add the certificate generation infrastructure needed by security examples

### PR DESCRIPTION
**Pull request by guyikcgg**
### Summary
Added `resource/cert` directory with 1 PKI: `ecdsa01`.

This PKI has 1 CA and 2 Peers. OpenSSL config files are provided for all 3 entities. A makefile is provided to generate certificates and keys for all 3 entities.

### Details and comments
No README has been generated.

### CODE REVIEW

**Comment by iblancasa** [comment]
I have some questions:
1) Should this example work for all the platforms?
2) Why are you implementing this with `gmake` instead of `CMake`?

**Comment by iblancasa** [comment]
I have a question: this PR was done to complete #282, right?

**Comment by guyikcgg** [comment]
@iblancasa That's right, the certificates generated by the code in this PR are needed to complete #282.

**Comment by guyikcgg** [comment]
@titosanxez The makefiles in this commit are pretty simple. I think they can be easily translated into CMake. Can someone help me do that?

**Comment by colmenero** [comment]
The infrastructure needed to generate an ECDSA CA and two peers will be provided once the [PR for the network capture examples](https://github.com/rticommunity/rticonnextdds-examples/pull/315) is approved and merged.

**Comment by colmenero** [comment]
@fgaranda I think we can remove this PR.
When the time comes, I will create a new one for improving the new infrastructure related to generating the security artifacts.
Thanks.

**Comment by fgaranda** [comment]
@colmenero will create a new PR that will leverage the CMake infrastructure to generate security artifacts.

**Pull request closed without merging**
